#! /bin/bash

tools_dir=tools
nuget_url=https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
nuget_path=$tools_dir/nuget.exe

if [ -e "$nuget_path" ] ; then
  echo "$nuget_path exists"
else
  echo "Installing NuGet to $nuget_path from $nuget_url"
  mkdir -p $tools_dir
  curl -L -o $nuget_path $nuget_url
fi
